'use client'

import { useState } from 'react'

interface Props {
  content: string
  onEdit: (updated: string) => void
  onRegenerate: () => void
  loading?: boolean
}

function renderMarkdown(text: string): string {
  return text
    .replace(/^## (.+)$/gm, '<h2 class="mt-6 mb-2 text-base font-bold text-gray-900 border-b border-gray-100 pb-1">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 class="mt-4 mb-1 text-sm font-semibold text-gray-800">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong class="font-semibold text-gray-900">$1</strong>')
    .replace(/\*(.+?)\*/g, '<em class="text-gray-500 text-xs">$1</em>')
    .replace(/^- (.+)$/gm, '<li class="ml-4 text-sm text-gray-700 leading-6 list-disc">$1</li>')
    .replace(/^(\d+)\. (.+)$/gm, '<li class="ml-4 text-sm text-gray-700 leading-6 list-decimal">$2</li>')
    .replace(/(<li.*<\/li>\n?)+/g, (m) => `<ul class="my-2 space-y-0.5">${m}</ul>`)
    .replace(/\n\n/g, '</p><p class="my-2 text-sm text-gray-700 leading-6">')
    .replace(/\n/g, '<br/>')
}

export default function AIResult({ content, onEdit, onRegenerate, loading }: Props) {
  const [editing, setEditing] = useState(false)
  const [editValue, setEditValue] = useState(content)
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleSaveEdit = () => {
    onEdit(editValue)
    setEditing(false)
  }

  const handleStartEdit = () => {
    setEditValue(content)
    setEditing(true)
  }

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center gap-3 rounded-2xl border border-brand-100 bg-brand-50 p-12 text-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-brand-200 border-t-brand-600" />
        <p className="text-sm font-medium text-brand-700">Generating with Grok AI...</p>
        <p className="text-xs text-brand-500">Usually takes 3–5 seconds</p>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-3">
      {/* Toolbar */}
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-xs font-semibold text-green-600 flex items-center gap-1">
          <span className="h-1.5 w-1.5 rounded-full bg-green-500 inline-block" />
          Generated by Grok AI
        </span>
        <div className="ml-auto flex gap-2">
          <button
            onClick={onRegenerate}
            className="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs font-medium text-gray-700 shadow-sm hover:bg-gray-50 transition"
          >
            <svg className="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
            </svg>
            Regenerate
          </button>
          <button
            onClick={editing ? handleSaveEdit : handleStartEdit}
            className="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs font-medium text-gray-700 shadow-sm hover:bg-gray-50 transition"
          >
            {editing ? (
              <>
                <svg className="h-3 w-3 text-green-600" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
                Save
              </>
            ) : (
              <>
                <svg className="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                </svg>
                Edit
              </>
            )}
          </button>
          {editing && (
            <button
              onClick={() => setEditing(false)}
              className="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs font-medium text-gray-500 shadow-sm hover:bg-gray-50 transition"
            >
              Cancel
            </button>
          )}
          <button
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 rounded-lg bg-brand-600 px-3 py-1.5 text-xs font-semibold text-white shadow-sm hover:bg-brand-700 transition"
          >
            {copied ? '✓ Copied!' : 'Copy All'}
          </button>
        </div>
      </div>

      {/* Content */}
      {editing ? (
        <textarea
          className="input-field min-h-[400px] resize-y font-mono text-xs leading-relaxed"
          value={editValue}
          onChange={(e) => setEditValue(e.target.value)}
        />
      ) : (
        <div
          className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm text-sm leading-7"
          dangerouslySetInnerHTML={{ __html: `<p class="my-2 text-sm text-gray-700 leading-6">${renderMarkdown(content)}</p>` }}
        />
      )}
    </div>
  )
}
