'use client'

import { useState } from 'react'

interface Props {
  content: string
  provider?: string
  onEdit: (updated: string) => void
  onRegenerate: () => void
  loading?: boolean
  plainText?: boolean // for proposal — no markdown rendering
}

function renderMarkdown(text: string): string {
  return text
    .replace(/^## (.+)$/gm, '<h2 class="mt-5 mb-1 text-sm font-bold text-gray-900 uppercase tracking-wide">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 class="mt-3 mb-1 text-sm font-semibold text-gray-800">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong class="font-semibold text-gray-900">$1</strong>')
    .replace(/\*(.+?)\*/g, '<em class="text-gray-500 text-xs">$1</em>')
    .replace(/^[-•] (.+)$/gm, '<li class="ml-4 text-sm text-gray-700 leading-6">$1</li>')
    .replace(/^(\d+)\. (.+)$/gm, '<li class="ml-4 text-sm text-gray-700 leading-6">$2</li>')
    .replace(/(<li.*<\/li>\n?)+/g, (m) => `<ul class="my-1 space-y-0.5 list-disc">${m}</ul>`)
    .replace(/\n\n/g, '<br/>')
    .replace(/\n/g, '<br/>')
}

const PROVIDER_LABELS: Record<string, string> = {
  'gemini': 'Gemini Flash',
  'meta-llama/llama-3.1-8b-instruct:free': 'Llama 3.1',
  'google/gemma-2-9b-it:free': 'Gemma 2',
  'mistralai/mistral-7b-instruct:free': 'Mistral',
  'template': 'Template',
}

export default function AIResult({ content, provider, onEdit, onRegenerate, loading, plainText }: Props) {
  const [editing, setEditing] = useState(false)
  const [editValue, setEditValue] = useState(content)
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleSaveEdit = () => {
    onEdit(editValue)
    setEditing(false)
  }

  const providerLabel = provider ? (PROVIDER_LABELS[provider] || provider) : 'AI'
  const isTemplate = provider === 'template'

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center gap-3 rounded-2xl border border-brand-100 bg-brand-50 p-12 text-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-brand-200 border-t-brand-600" />
        <p className="text-sm font-medium text-brand-700">Generating...</p>
        <p className="text-xs text-brand-500">Usually takes 3–8 seconds</p>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-2">
      {/* Toolbar */}
      <div className="flex flex-wrap items-center gap-2">
        <span className={`text-xs font-medium flex items-center gap-1 ${isTemplate ? 'text-gray-400' : 'text-green-600'}`}>
          <span className={`h-1.5 w-1.5 rounded-full inline-block ${isTemplate ? 'bg-gray-400' : 'bg-green-500'}`} />
          {isTemplate ? 'Template (AI unavailable)' : `Generated by ${providerLabel}`}
        </span>
        <div className="ml-auto flex gap-2">
          <button onClick={onRegenerate}
            className="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-50 transition">
            ↺ Regenerate
          </button>
          <button onClick={editing ? handleSaveEdit : () => { setEditValue(content); setEditing(true) }}
            className="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-50 transition">
            {editing ? '✓ Save' : '✎ Edit'}
          </button>
          {editing && (
            <button onClick={() => setEditing(false)}
              className="inline-flex items-center rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs text-gray-500 hover:bg-gray-50 transition">
              Cancel
            </button>
          )}
          <button onClick={handleCopy}
            className="inline-flex items-center gap-1.5 rounded-lg bg-brand-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-brand-700 transition">
            {copied ? '✓ Copied!' : 'Copy All'}
          </button>
        </div>
      </div>

      {/* Content */}
      {editing ? (
        <textarea
          className="input-field min-h-[360px] resize-y text-sm leading-relaxed"
          value={editValue}
          onChange={(e) => setEditValue(e.target.value)}
        />
      ) : plainText ? (
        // Plain text mode for proposals — no markdown, clean whitespace
        <div className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm">
          {content.split('\n\n').map((para, i) => (
            para.trim() ? (
              <p key={i} className="mb-4 text-sm leading-7 text-gray-800 last:mb-0">{para.trim()}</p>
            ) : null
          ))}
        </div>
      ) : (
        // Markdown mode for SOW, discovery, questionnaire
        <div
          className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm text-sm leading-7"
          dangerouslySetInnerHTML={{ __html: renderMarkdown(content) }}
        />
      )}
    </div>
  )
}
