'use client'

import { useState } from 'react'

interface ContractData {
  freelancerName: string
  clientName: string
  projectTitle: string
  scope: string
  deliverables: string
  startDate: string
  endDate: string
  paymentType: 'flat' | 'milestone' | 'hourly'
  totalAmount: string
  depositPercent: number
  revisions: number
  killFeePercent: number
  ipOwnership: 'client' | 'freelancer' | 'licensed'
  jurisdiction: string
}

function generateContract(d: ContractData): string {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const deposit = d.paymentType !== 'hourly' && d.totalAmount
    ? `$${(parseFloat(d.totalAmount.replace(/[^0-9.]/g, '')) * d.depositPercent / 100).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
    : 'N/A'

  const ipClause =
    d.ipOwnership === 'client'
      ? 'Upon receipt of full payment, Freelancer assigns all intellectual property rights in the deliverables to Client.'
      : d.ipOwnership === 'licensed'
      ? 'Freelancer retains ownership of all intellectual property. Client is granted a non-exclusive, perpetual license to use the deliverables for the agreed purpose.'
      : 'Freelancer retains full ownership of all intellectual property. Client receives a limited license to use final deliverables as delivered.'

  const paymentClause =
    d.paymentType === 'flat'
      ? `Client agrees to pay a flat fee of $${d.totalAmount} for the completed project. A deposit of ${d.depositPercent}% (${deposit}) is due upon signing. The remaining balance is due upon delivery of final files.`
      : d.paymentType === 'milestone'
      ? `Client agrees to pay $${d.totalAmount} total, split across project milestones. A deposit of ${d.depositPercent}% (${deposit}) is due upon signing. Remaining payments are due at each agreed milestone as outlined in the project brief.`
      : `Client agrees to pay Freelancer at an agreed hourly rate. Invoices will be issued [weekly/bi-weekly/monthly] and are due within 7 days of receipt.`

  return `FREELANCE SERVICES AGREEMENT

Effective Date: ${today}

PARTIES
This Freelance Services Agreement ("Agreement") is entered into between:

Freelancer: ${d.freelancerName || '[Your Name / Business Name]'}
Client: ${d.clientName || '[Client Name / Company]'}

PROJECT
Project Title: ${d.projectTitle || '[Project Name]'}
Start Date: ${d.startDate || '[Start Date]'}
Target Completion Date: ${d.endDate || '[End Date]'}

1. SCOPE OF WORK
${d.scope || '[Describe the overall project scope here.]'}

2. DELIVERABLES
The following deliverables are included in this Agreement:
${d.deliverables || '[List specific deliverables here.]'}

3. PAYMENT TERMS
${paymentClause}

Late payments are subject to a 1.5% monthly interest charge on the outstanding balance. Freelancer reserves the right to pause work on accounts more than 14 days past due.

4. REVISIONS
This Agreement includes ${d.revisions} round(s) of revisions. A revision is defined as minor changes to approved work. Additional revision rounds beyond this limit will be billed at Freelancer's standard hourly rate.

5. CANCELLATION / KILL FEE
If Client cancels this project after work has commenced, Client agrees to pay a kill fee of ${d.killFeePercent}% of the remaining contract value to compensate Freelancer for time and opportunity costs incurred.

6. INTELLECTUAL PROPERTY
${ipClause}

7. CONFIDENTIALITY
Both parties agree to keep confidential any proprietary information, business data, or trade secrets shared during this engagement and not to disclose such information to third parties without prior written consent.

8. INDEPENDENT CONTRACTOR
Freelancer is an independent contractor, not an employee of Client. Freelancer is responsible for all taxes on income received under this Agreement.

9. LIMITATION OF LIABILITY
Freelancer's total liability under this Agreement shall not exceed the total fees paid by Client. Freelancer is not liable for indirect, incidental, or consequential damages.

10. GOVERNING LAW
This Agreement shall be governed by the laws of ${d.jurisdiction || '[Your State / Country]'}.

11. ENTIRE AGREEMENT
This Agreement constitutes the entire agreement between the parties and supersedes any prior discussions, proposals, or agreements.

─────────────────────────────────────────────

SIGNATURES

Freelancer: _________________________  Date: ___________
${d.freelancerName || '[Your Name]'}

Client: _____________________________  Date: ___________
${d.clientName || '[Client Name]'}

─────────────────────────────────────────────
Generated by FreelTools.com — Not legal advice. Have your contract reviewed by a qualified attorney.`
}

export default function FreelanceContractGenerator() {
  const [data, setData] = useState<ContractData>({
    freelancerName: '',
    clientName: '',
    projectTitle: '',
    scope: '',
    deliverables: '',
    startDate: '',
    endDate: '',
    paymentType: 'flat',
    totalAmount: '',
    depositPercent: 50,
    revisions: 2,
    killFeePercent: 25,
    ipOwnership: 'client',
    jurisdiction: '',
  })
  const [generated, setGenerated] = useState(false)
  const [copied, setCopied] = useState(false)

  const contract = generateContract(data)

  const set = (field: keyof ContractData) => (val: string | number) =>
    setData((prev) => ({ ...prev, [field]: val }))

  const handleCopy = () => {
    navigator.clipboard.writeText(contract)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const inputCls = 'input-field h-10'
  const textareaCls = 'w-full rounded-lg border border-gray-200 bg-white px-3 py-2.5 text-sm text-gray-900 placeholder-gray-400 focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-200 resize-none'

  return (
    <div className="space-y-8">
      <div className="grid gap-8 lg:grid-cols-2">
        {/* Inputs */}
        <div className="space-y-5 rounded-2xl border border-gray-100 bg-white p-6 shadow-sm">
          <h2 className="text-base font-semibold text-gray-900">Project & Party Details</h2>

          <div>
            <label className="mb-1.5 block text-sm font-medium text-gray-700">Your Name / Business Name</label>
            <input className={inputCls} placeholder="Jane Smith Design" value={data.freelancerName} onChange={(e) => set('freelancerName')(e.target.value)} />
          </div>
          <div>
            <label className="mb-1.5 block text-sm font-medium text-gray-700">Client Name / Company</label>
            <input className={inputCls} placeholder="Acme Corp" value={data.clientName} onChange={(e) => set('clientName')(e.target.value)} />
          </div>
          <div>
            <label className="mb-1.5 block text-sm font-medium text-gray-700">Project Title</label>
            <input className={inputCls} placeholder="Website Redesign" value={data.projectTitle} onChange={(e) => set('projectTitle')(e.target.value)} />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="mb-1.5 block text-sm font-medium text-gray-700">Start Date</label>
              <input type="date" className={inputCls} value={data.startDate} onChange={(e) => set('startDate')(e.target.value)} />
            </div>
            <div>
              <label className="mb-1.5 block text-sm font-medium text-gray-700">End Date</label>
              <input type="date" className={inputCls} value={data.endDate} onChange={(e) => set('endDate')(e.target.value)} />
            </div>
          </div>
          <div>
            <label className="mb-1.5 block text-sm font-medium text-gray-700">Project Scope</label>
            <textarea className={textareaCls} rows={3} placeholder="Describe what the project involves..." value={data.scope} onChange={(e) => set('scope')(e.target.value)} />
          </div>
          <div>
            <label className="mb-1.5 block text-sm font-medium text-gray-700">Deliverables</label>
            <textarea className={textareaCls} rows={3} placeholder="List what you'll deliver (one per line)" value={data.deliverables} onChange={(e) => set('deliverables')(e.target.value)} />
          </div>
        </div>

        {/* Payment & Terms */}
        <div className="space-y-5 rounded-2xl border border-gray-100 bg-white p-6 shadow-sm">
          <h2 className="text-base font-semibold text-gray-900">Payment & Terms</h2>

          <div>
            <label className="mb-1.5 block text-sm font-medium text-gray-700">Payment Structure</label>
            <select className={inputCls} value={data.paymentType} onChange={(e) => set('paymentType')(e.target.value)}>
              <option value="flat">Flat Fee</option>
              <option value="milestone">Milestone-Based</option>
              <option value="hourly">Hourly Rate</option>
            </select>
          </div>

          {data.paymentType !== 'hourly' && (
            <>
              <div>
                <label className="mb-1.5 block text-sm font-medium text-gray-700">Total Project Amount ($)</label>
                <input className={inputCls} type="number" min={0} placeholder="5000" value={data.totalAmount} onChange={(e) => set('totalAmount')(e.target.value)} />
              </div>
              <div>
                <label className="mb-1.5 block text-sm font-medium text-gray-700">Deposit Percentage: {data.depositPercent}%</label>
                <input type="range" min={10} max={100} step={5} value={data.depositPercent} onChange={(e) => set('depositPercent')(Number(e.target.value))} className="w-full accent-indigo-600" />
                <div className="flex justify-between text-xs text-gray-400 mt-1"><span>10%</span><span>50%</span><span>100%</span></div>
              </div>
            </>
          )}

          <div>
            <label className="mb-1.5 block text-sm font-medium text-gray-700">Revision Rounds Included: {data.revisions}</label>
            <input type="range" min={0} max={10} value={data.revisions} onChange={(e) => set('revisions')(Number(e.target.value))} className="w-full accent-indigo-600" />
            <div className="flex justify-between text-xs text-gray-400 mt-1"><span>0</span><span>5</span><span>10</span></div>
          </div>

          <div>
            <label className="mb-1.5 block text-sm font-medium text-gray-700">Kill Fee (Cancellation): {data.killFeePercent}%</label>
            <input type="range" min={0} max={100} step={5} value={data.killFeePercent} onChange={(e) => set('killFeePercent')(Number(e.target.value))} className="w-full accent-indigo-600" />
          </div>

          <div>
            <label className="mb-1.5 block text-sm font-medium text-gray-700">IP Ownership</label>
            <select className={inputCls} value={data.ipOwnership} onChange={(e) => set('ipOwnership')(e.target.value)}>
              <option value="client">Client owns IP (full assignment on payment)</option>
              <option value="licensed">Freelancer owns, client gets license</option>
              <option value="freelancer">Freelancer retains all rights</option>
            </select>
          </div>

          <div>
            <label className="mb-1.5 block text-sm font-medium text-gray-700">Governing Jurisdiction</label>
            <input className={inputCls} placeholder="e.g., State of California, USA" value={data.jurisdiction} onChange={(e) => set('jurisdiction')(e.target.value)} />
          </div>

          <button
            onClick={() => setGenerated(true)}
            className="w-full rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white hover:bg-indigo-700 transition"
          >
            Generate Contract →
          </button>
        </div>
      </div>

      {/* Generated Contract */}
      {generated && (
        <div className="rounded-2xl border border-gray-200 bg-white shadow-sm">
          <div className="flex items-center justify-between border-b border-gray-100 px-6 py-4">
            <h2 className="text-base font-semibold text-gray-900">Your Contract</h2>
            <button
              onClick={handleCopy}
              className="rounded-lg border border-gray-200 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition"
            >
              {copied ? '✓ Copied!' : 'Copy to Clipboard'}
            </button>
          </div>
          <pre className="whitespace-pre-wrap p-6 font-mono text-xs leading-relaxed text-gray-700 sm:text-sm">
            {contract}
          </pre>
        </div>
      )}
    </div>
  )
}
